### PR TITLE
HSC-123: Change Materials to Stockable Products

### PR DESCRIPTION
**Pull request by nuhuhmutebi**

### CODE REVIEW

**Review by rbuisson — COMMENTED** [review]
@nuhuhmutebi , in the OpenMRS Config, it seems that you have added much more materials than simply moving them out from the Procedures & Materials.

Haven't we say that, for now, EMR users won't be ordering Materials? And this instead will be either guessed by the Pharmacy (based on the procedure ordered) or they will communicate ordered items by other means (paper)?

**Comment by nuhuhmutebi** [comment]
Hi @rbuisson, concerning this, Marcelle finally decided that we add these Materials to the EMR since not all materials can be determined based on the procedure. I actually informed you about it in [this](https://mekomsolutions.slack.com/archives/G421UNF5L/p1686841365893579?thread_ts=1686826473.003099&cid=G421UNF5L) thread here. Maybe you were somehow more engaged.

**Comment by nuhuhmutebi** [comment]
| in the OpenMRS Config, it seems that you have added much more materials than simply moving them out from the Procedures & Materials
Concerning the above, there were just a few Materials that had been added as Procedures.

**Comment by rbuisson** [comment]
Sorry for not jumping on this message on Slack.
Issue with ordering products on the OpenMRS side is that there is no field to enter the quantity in a proper way. Does the client know about this?

**Comment by rbuisson** [comment]
So from discussing with @nuhuhmutebi , we will record the Quantity as in the order note for now.

**Review by rbuisson — APPROVED** [review]

**Pull request merged**
