### PR TITLE
HSC-222: Make all Motif de Consultation form fields mandatory

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/HSC-222)

### CODE REVIEW

**Comment by kazlaw** [comment]
[Screencast from 01-03-24 14:08:44.webm](https://github.com/CRUDEM/openmrs-config-hsc/assets/36139599/201f3af0-4bb6-45b2-a951-6a557ce0e343)

@Ruhanga this is ready for review

**Comment by Ruhanga** [comment]
@kazlaw from the screen recording, I get the impression that the field `Motif de consultation` is not mandatory, is that correct?

**Comment by kazlaw** [comment]
When you set it to mandatory the field doesn't save. However with each selection you make the details field pops up and its mandatory so it's technically mandatory. @Ruhanga

**Comment by Ruhanga** [comment]
> so it's technically mandatory.

What happens when you fill in the rest of the form and just leave out `Motif de consultation`? Does the form not save?

**Comment by kazlaw** [comment]
> > so it's technically mandatory.
> 
> What happens when you fill in the rest of the form and just leave out `Motif de consultation`? Does the form not save?

It doesn't save

**Review by Ruhanga — APPROVED** [review]

**Pull request merged**
