### PR TITLE
HSC-225: Fixed form reference uuid and version for Examen des Systemes form

### PR DESCRIPTION
**Pull request by kazlaw**
Link to ticket here -->https://mekomsolutions.atlassian.net/browse/HSC-225

[Screencast from 10-04-24 17:15:08.webm](https://github.com/CRUDEM/openmrs-config-hsc/assets/36139599/40191f57-f585-4969-b8ab-f19a9143d85a)

### CODE REVIEW

**Comment by kazlaw** [comment]
@Ruhanga the fix is to remove the error which pops up concerning the locale string when you view the visit details

**Review by Ruhanga — COMMENTED** [review]
How many/which forms are affected with the changes made here @kazlaw?

**Comment by kazlaw** [comment]
Sorry pushed on the wrong branch. Let me fix it

**Comment by kazlaw** [comment]
@Ruhanga please use this new PR [here](https://github.com/CRUDEM/openmrs-config-hsc/pull/73)

**Pull request closed without merging**
